name    'morphizer-sickbeard'
version '0.0.1'
source 'http://sickbeard.com/'
author 'morphizer'
license 'Apache License, Version 2.0'
summary 'SickBeard PVR application that searches for and manages your TV shows'
description 'SickBeard PVR application that searches for and manages your TV shows'
project_page 'blank'

dependency 'puppetlabs/vcsrepo', '>= 0.1.1'
